import 'package:flutter/material.dart';
import '../psychiatrist_dashboard/repository.dart';

class GPMedicalCertificateForm extends StatefulWidget {
  final String appointmentId;
  final String patientName;

  const GPMedicalCertificateForm({
    super.key,
    required this.appointmentId,
    required this.patientName,
  });

  @override
  State<GPMedicalCertificateForm> createState() => _GPMedicalCertificateFormState();
}

class _GPMedicalCertificateFormState extends State<GPMedicalCertificateForm> {
  final _formKey = GlobalKey<FormState>();
  final _daysCtrl = TextEditingController(text: '1');
  final _reasonCtrl = TextEditingController();
  final _commentsCtrl = TextEditingController();
  DateTime _startDate = DateTime.now();

  bool _isSaving = false;

  void _generateCertificate() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSaving = true);

    final endDate = _startDate.add(Duration(days: int.parse(_daysCtrl.text) - 1));

    // Special header so the UI can detect and render this uniquely
    final noteText = '''
*** OFFICIAL MEDICAL CERTIFICATE ***
**Patient:** ${widget.patientName}
**Recommended Days Off:** ${_daysCtrl.text} day(s)
**Start Date:** ${_startDate.toLocal().toString().split(' ')[0]}
**End Date:** ${endDate.toLocal().toString().split(' ')[0]}

**Reason / Condition:**
${_reasonCtrl.text.trim().isNotEmpty ? _reasonCtrl.text.trim() : 'Medical Illness'}

**Additional Comments:**
${_commentsCtrl.text.trim().isNotEmpty ? _commentsCtrl.text.trim() : 'None.'}

*This certificate was electronically generated by the NUST Campus Health system.*
    '''.trim();

    await repository.addNote(widget.appointmentId, noteText);

    if (mounted) {
      setState(() => _isSaving = false);
      Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Medical Certificate generated successfully'),
          backgroundColor: Colors.green,
        ),
      );
    }
  }

  Future<void> _pickDate(BuildContext context) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _startDate,
      firstDate: DateTime.now().subtract(const Duration(days: 30)),
      lastDate: DateTime.now().add(const Duration(days: 30)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: Color(0xFF004D40), // Dark Teal
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null && picked != _startDate) {
      setState(() {
        _startDate = picked;
      });
    }
  }

  @override
  void dispose() {
    _daysCtrl.dispose();
    _reasonCtrl.dispose();
    _commentsCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
        left: 20,
        right: 20,
        top: 20,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.verified, color: Color(0xFF004D40)),
                      const SizedBox(width: 8),
                      const Text(
                        'Issue Sick Note',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF004D40),
                        ),
                      ),
                    ],
                  ),
                  IconButton(
                    onPressed: () => Navigator.pop(context),
                    icon: const Icon(Icons.close),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    flex: 1,
                    child: TextFormField(
                      controller: _daysCtrl,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Days Off',
                        prefixIcon: Icon(Icons.event_busy),
                        border: OutlineInputBorder(),
                      ),
                      validator: (v) {
                        if (v == null || v.isEmpty) return 'Required';
                        if (int.tryParse(v) == null || int.parse(v) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 2,
                    child: InkWell(
                      onTap: () => _pickDate(context),
                      child: InputDecorator(
                        decoration: const InputDecoration(
                          labelText: 'Start Date',
                          prefixIcon: Icon(Icons.calendar_today),
                          border: OutlineInputBorder(),
                        ),
                        child: Text(
                          _startDate.toLocal().toString().split(' ')[0],
                          style: const TextStyle(fontSize: 16),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _reasonCtrl,
                decoration: const InputDecoration(
                  labelText: 'Condition / Reason (Optional)',
                  hintText: 'e.g. Severe flu, Migraine',
                  prefixIcon: Icon(Icons.medical_services),
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _commentsCtrl,
                maxLines: 3,
                decoration: const InputDecoration(
                  labelText: 'Additional Comments (Optional)',
                  alignLabelWithHint: true,
                  prefixIcon: Icon(Icons.notes),
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _isSaving ? null : _generateCertificate,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF004D40),
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                child: _isSaving
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text(
                        'Generate Certificate',
                        style: TextStyle(fontSize: 16, color: Colors.white),
                      ),
              ),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }
}
